export const LOAD_DATA = 'LOAD_DATA';
export type LOAD_DATA = typeof LOAD_DATA;

export const FETCHING_DATA = 'FETCHING_DATA';
export type FETCHING_DATA = typeof FETCHING_DATA;

export const FETCHINT_DATA_SUCCESS = 'FETCHINT_DATA_SUCCESS';
export type FETCHINT_DATA_SUCCESS = typeof FETCHINT_DATA_SUCCESS;

export const RECIEVE_ERROR = 'RECIEVE_ERROR ';
export type RECIEVE_ERROR = typeof RECIEVE_ERROR;

export const GET_USER_LIST = 'GET_USER_LIST';
export type GET_USER_LIST = typeof GET_USER_LIST;

export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export type LOAD_INITIAL_DATA = typeof LOAD_INITIAL_DATA;

export const LOAD_ALL_USER_LIST = 'LOAD_ALL_USER_LIST';
export type LOAD_ALL_USER_LIST = typeof LOAD_ALL_USER_LIST;

export const LOAD_FILTERED_USER_LIST = 'LOAD_FILTERED_USER_LIST';
export type LOAD_FILTERED_USER_LIST = typeof LOAD_FILTERED_USER_LIST;

export const GET_ALL_USER_SUMMARY = 'GET_ALL_USER_SUMMARY';
export type GET_ALL_USER_SUMMARY = typeof GET_ALL_USER_SUMMARY;

export const GET_FILTERED_USER_SUMMARY = 'GET_FILTERED_USER_SUMMARY';
export type GET_FILTERED_USER_SUMMARY = typeof GET_FILTERED_USER_SUMMARY;

export const GET_ALL_USER_BAR_GRAPH = 'GET_ALL_USER_BAR_GRAPH';
export type GET_ALL_USER_BAR_GRAPH = typeof GET_ALL_USER_BAR_GRAPH;

export const GET_FILTERED_USER_BAR_GRAPH = 'GET_FILTERED_USER_BAR_GRAPH';
export type GET_FILTERED_USER_BAR_GRAPH = typeof GET_FILTERED_USER_BAR_GRAPH;

export const TOGGLE_ANIMATION = 'TOGGLE_ANIMATION';
export type TOGGLE_ANIMATION = typeof TOGGLE_ANIMATION;
